### ISSUE TITLE
Possible incorrect link in getting started tutorial 

### ISSUE THREAD

**Issue by roberttoyonaga** [cryostatio/cryostatio.github.io#151]
I think I may have found a minor website bug: I think the hyperlink for the text "continue to the next step" in [this website getting-started section](https://cryostat.io/get-started/#deploy-an-application) links you to the wrong location. It links me backwards instead of forwards. 

Correct link: https://cryostat.io/get-started/#configuring-applications

Actual link: https://cryostat.io/get-started/#open-the-cryostat-web-ui

**Comment by aali309** [comment]
@andrewazores should I add this on my [PR#150](https://github.com/cryostatio/cryostatio.github.io/pull/150) or a new PR?

**Comment by andrewazores** [comment]
Good catch @roberttoyonaga , what you say looks right to me. If the user has other existing applications they want to use with Cryostat then they should continue to configuring those, not jumping straight in to opening the Cryostat web UI, otherwise they'll be looking at a mostly-useless Cryostat installation that only sees itself, if anything.

@aali309 you can add this to your existing PR

**Comment by aali309** [comment]
I think this issue can be closed? Fixed by [This Commit](https://github.com/cryostatio/cryostatio.github.io/pull/150/commits/74cd6635690ea7f5d1aad49664c43a51a83a1894)

**Comment by andrewazores** [comment]
That commit hasn't landed in `main` yet, so this issue shouldn't be closed until it does, but yes the work required is already completed.
